### PR TITLE
MacOS debug symbols support

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by karianna** [comment]
@andrew-m-leonard I thought we'd already done this no?

**Comment by andrew-m-leonard** [comment]
@karianna  It needs merging into the "release" branch as well, as upstream contribution is in jdk8u302 not the April jdk8u292, so will fail to build April release without this...

**Comment by andrew-m-leonard** [comment]
Successful test build: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-hotspot/963/console

**Comment by andrew-m-leonard** [comment]
@karianna this is good to merge please if you're happy?

**Pull request merged**
